name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: Set up Docker
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u toshi0607 --password-stdin

      - name: Set up Kubernetes cluster with kind
        uses: helm/kind-action@v1

      - name: e2e test
        run: |
          export KUBECONFIG="${HOME}/.kube/config"
          make test_e2e
        env:
          JCTL_DOCKER_REPO: toshi0607
